<?php
    return array(
        'main' => 'Main',
        'organizing_committee' => 'Organizing Committee ',
        'announcements' => 'Announcements',
        'collections_materials' => 'Сonference proceedings ',
        'conference_archive' => 'Conference archive',
        'contacts' => 'Contacts',
        'application_f' => 'Application form',
        'application_s' => 'Submit a paper',
        'title_f' => 'INTERNATIONAL PRACTICAL SCIENCE CONFERENCE',
        'title_s' => '"LANGUAGE. CULTURE. TRANSLATION"',
        'title_faculty' => 'School of Linguistics and Cross-Cultural Communication, MGIMO University',
        'faculty_inf' => 'School of Linguistics and Cross-Cultural Communication, MGIMO Odintsovo branch, was founded on July 1, 2017, blending traditions of MGIMO language training and innovations of modern linguistic education. The educational programs taught at the department allow you to get a high-quality linguistic education and knowledge of the peculiarities of foreign cultures, gain practical experience of professional translation, become a specialist in cross-cultural communication for specific purposes, and learn how to work in an international team using several foreign languages.',
        'faculty_link' => 'https://english.mgimo.ru/structure/schools/school-of-linguistics-and-cross-cultural-communication',
        'title_conference' => 'About the Conference',
        'info_conference' => 'In 2018, School of Linguistics and Cross-Cultural Communication (L&CCC) started hosting annual discussions on the most urgent results, issues and prospects of linguistic research conducted by both domestic and foreign scientific and practical schools. The events take place in February or March.
        </br></br>
        In 2018 linguists met in the framework of an inter-university seminar; in 2019 an all-Russian practical science conference was organized; in 2020 the International practical science “Language. Culture. Translation: Research paradigms and practical aspects”.
        </br></br>
        Starting from 2021, it was decided to hold an International Practical Science Seminar (up to four sections) in a hybrid form (online + offline) every odd year, and an International practical science conference (more than eight sections) every even year.',
        'but_more' => 'More',
        'facprog_titl' => 'About School Programs',
        'f_prog' => 'BA Program',
        's_prog' => 'MA Program',
        'f_prog_text' => 'The Bachelor`s degree program “Translation, Linguistic and Cultural Studies, and Cross-Cultural Communication (in Russian and English)” includes several subject modules — diplomatic, linguistic, international, regional studies, and "digital". Much attention is paid to foreign and domestic regional studies and linguistics.',
        's_prog_text' => 'The new master`s program "Translation and Modern Technologies in Linguistics" combines the best components of linguistic master`s programs in translation and cross-cultural communication of previous years of recruitment and adds a "digital" track. Relevance of the master`s program is determined by modern challenges — the need to train linguists-translators and linguistic experts who provide immediate and remote cross-cultural communication with the help of modern digital tools and technologies.',
        'orgcomitet' => 'Organizing Committee',
        'announcement_title_f' => 'Upcoming conference',
        'y' => ' ',
        'announcement_title_s' => 'Announcement',
        'last_ph' => 'Recent photos',
        'last_conf' => 'Recent conferences',
        'where' => 'How to find us',
        'address' => 'Address',
        'address_text' => '143007 Moscovskaya Oblast, Odintsovsky District, Odintsovo, Novo-Sportivnaya Street, 3 (room 516)',
        'phone' => 'Phone',
        'phone_text' => '+7 495 661 71 98',
        'footer' => 'Odintsovo branch of MGIMO © 2021',
        'el_collection' => 'Conference proceedings',
        'conf' => 'Conference',
        'download' => 'Download',
        'download_el' => 'Download',
        'read_el' => 'Read at elibrary',
        'year' => ' ',
        'feed' => 'Reviews',
        'speak' => 'Plenary session speakers',
        'but_read' => 'Read about the event',
        'video' => 'Videos',
        'photo' => 'Photos',
        'arch' => 'Archive',
        'collect' => 'Collection of electronic materials',
        'no_conf' => 'There are no upcoming conferences',
        'conception' => 'About the Conference',
        'speakers' => 'Speakers',
        'dates' => 'Key dates',
        'more' => 'more',
        'contact' => 'Contact us',
        'partner' => 'Conference Partners',
        'nextconf' => 'Next Conference:',
        'date' => 'February 17-18, 2022',
    );
?>